FROM python:3.12

WORKDIR /app

RUN pip install --no-cache-dir uv 

COPY pyproject.toml uv.lock  ./


RUN apt-get update && apt-get install -y \
    libpq-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

RUN uv sync

COPY . . 

EXPOSE  8000

LABEL   NAME="FASTAPI APPLICATIN" \
        VERSION="1.0.0" \
        DESCRIPTION="A SIMPLE CONTAINER" \
        AUTHOR="ANJUM HASEEB" 

CMD [ "uv", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload" ]